# Generated by Django 3.0.2 on 2020-09-26 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('E_no', models.IntegerField()),
                ('First_name', models.CharField(max_length=30)),
                ('Last_name', models.CharField(max_length=20)),
                ('E_salary', models.FloatField()),
                ('Contact_no', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Country', models.CharField(max_length=20)),
                ('City', models.CharField(max_length=30)),
                ('Pin_code', models.IntegerField()),
                ('Address', models.CharField(max_length=150)),
            ],
        ),
    ]
