# Generated by Django 3.0.2 on 2020-09-27 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('E_no', models.IntegerField()),
                ('E_name', models.CharField(max_length=30)),
                ('In_date', models.FloatField()),
                ('Out_date', models.FloatField()),
                ('Description', models.CharField(max_length=120)),
            ],
        ),
    ]
