# Generated by Django 3.0.2 on 2020-09-27 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dApp', '0002_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='In_date',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='Out_date',
            field=models.IntegerField(),
        ),
    ]
